Task-1

In [ ]:
battery_data =  [[0, 32, 400, 20, 95],
                 [1, 35, 395, 22, 88],
                 [2, 38, 390, 25, 80],
                 [3, 40, 385, 28, 70],
                 [4, 42, 380, 30, 60],
                 [5, 45, 375, 32, 48]]
for reading in battery_data:
    print(
        "Time:", reading[0],
        "h, Temperature:", reading[1],
        "°C, Voltage:", reading[2],
        "V, Current:", reading[3],
        "A, Charge:", reading[4],
        "%"
    )


Time: 0 h, Temperature: 32 °C, Voltage: 400 V, Current: 20 A, Charge: 95 %
Time: 1 h, Temperature: 35 °C, Voltage: 395 V, Current: 22 A, Charge: 88 %
Time: 2 h, Temperature: 38 °C, Voltage: 390 V, Current: 25 A, Charge: 80 %
Time: 3 h, Temperature: 40 °C, Voltage: 385 V, Current: 28 A, Charge: 70 %
Time: 4 h, Temperature: 42 °C, Voltage: 380 V, Current: 30 A, Charge: 60 %
Time: 5 h, Temperature: 45 °C, Voltage: 375 V, Current: 32 A, Charge: 48 %


In [ ]:
for reading in battery_data:
    temperature = reading[1]

    if temperature > 40:
        print(reading[0], "h: High Temperature Alert")
    else:
        print(reading[0], "h: Temperature Normal")


0 h: Temperature Normal
1 h: Temperature Normal
2 h: Temperature Normal
3 h: Temperature Normal
4 h: High Temperature Alert
5 h: High Temperature Alert


In [ ]:
for reading in battery_data:
    charge = reading[4]

    if charge < 50:
        print(reading[0], "h: Low Battery Alert")
    else:
        print(reading[0], "h: Battery Charge Normal")

0 h: Battery Charge Normal
1 h: Battery Charge Normal
2 h: Battery Charge Normal
3 h: Battery Charge Normal
4 h: Battery Charge Normal
5 h: Low Battery Alert


In [ ]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"

for reading in battery_data:
    print(reading[0], "h:", battery_status(reading[4]))

0 h: High
1 h: High
2 h: High
3 h: Medium
4 h: Medium
5 h: Low


Task-2

In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(D)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


In [ ]:
print(D.shape)

(6, 4)


In [ ]:
averages = np.mean(D, axis=0)
print("Average Temperature:", averages[0])
print("Average Voltage:", averages[1])
print("Average Current:", averages[2])
print("Average Charge:", averages[3])


Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


In [ ]:
T_max = np.max(D[:, 0])
T_min = np.min(D[:, 0])
print("Maximum Temperature:", T_max)
print("Minimum Temperature:", T_min)


Maximum Temperature: 45
Minimum Temperature: 32


In [ ]:
voltage = D[:, 1]
print(voltage)


[400 395 390 385 380 375]


In [ ]:
high_temperature = D[D[:, 0] > 40]
print(high_temperature)

[[ 42 380  30  60]
 [ 45 375  32  48]]


In [ ]:
low_battery = D[D[:, 3] < 50]
print(low_battery)

[[ 45 375  32  48]]


Task-3

In [ ]:
A = np.array([
    [2, 1],
    [1, 3]
])
X = np.array([
    [40],
    [25]
])

Y = A @ X

print(Y)


[[105]
 [115]]


In [ ]:
print(A.T)

[[2 1]
 [1 3]]


In [ ]:
det_A = np.linalg.det(A)
print(det_A)

5.000000000000001


In [ ]:
google.com/mail/u/0/#search/vineela?projector=1

[[ 0.6 -0.2]
 [-0.2  0.4]]


In [ ]:
A = np.array([
    [2, 1],
    [1, 3]
])

B = np.array([100, 120])
solution = np.linalg.solve(A, B)
print("x =", solution[0])
print("y =", solution[1])

x = 36.0
y = 28.0


Task-4

In [ ]:
import sympy as sp
t = sp.symbols('t')
C = 100 - 2*t - (1/2)*t**2
dC_dt = sp.diff(C, t)
print("Battery Charge Function:", C)
print("Rate of Change dC/dt:", dC_dt)

Battery Charge Function: -0.5*t**2 - 2*t + 100
Rate of Change dC/dt: -1.0*t - 2


In [ ]:
import sympy as sp
t = sp.symbols('t')
C = 100 - 2*t - (1/2)*t**2
dC_dt = sp.diff(C, t)
rate_2 = dC_dt.subs(t, 2)
rate_5 = dC_dt.subs(t, 5)
print("Discharge rate at t = 2:", rate_2, "% per hour")
print("Discharge rate at t = 5:", rate_5, "% per hour")

Discharge rate at t = 2: -4.00000000000000 % per hour
Discharge rate at t = 5: -7.00000000000000 % per hour


In [ ]:
import sympy as sp
t-sp.symbols('t')
C=100-2*t-(1/2)*t**2
dC_dt=sp.diff(C,t)
print("Battery Charge Function:")
print("C(t)=",C)
print("\nRate of Change:")
print("dC/dt=",dC_dt)
rate_2=dC_dt.subs(t,2)
rate_5=dC_dt.subs(t,5)
print("\nDischarge Rate at t=2:")
print(rate_2, "% per hour")
print("\nDischarge Rate at t=5:")
print(rate_5,"% per hour")
if abs(rate_5)>abs(rate_2):
  print("\nInterpretation: Battery is losing charge at an increasing rate. ")
elif abs(rate_5)<abs(rate_2):
  print("\nInterpretation: Battery is losing charge at a decreasing rate.")
else:
  print("Intepreatation: Battery is losing charge at a constant rate.")


Battery Charge Function:
C(t)= -0.5*t**2 - 2*t + 100

Rate of Change:
dC/dt= -1.0*t - 2

Discharge Rate at t=2:
-4.00000000000000 % per hour

Discharge Rate at t=5:
-7.00000000000000 % per hour

Interpretation: Battery is losing charge at an increasing rate. 
